# Generated by Django 3.2.2 on 2021-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0002_clickmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickmodel',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clickmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
